### ISSUE TITLE
不能在iOS8.0以下的系统运行，原因是编译宏不对__IPHONE_OS_VERSION_MAX_ALLOWED

### ISSUE THREAD

**Issue by qimuya3** [devedbox/AXWebViewController#1]
// 当前SDK系统支持的最小版本
__IPHONE_OS_VERSION_MIN_REQUIRED
// 当前SDK系统支持的最大版本
__IPHONE_OS_VERSION_MAX_ALLOWED

所以，不能通过__IPHONE_OS_VERSION_MAX_ALLOWED来进行编译控制，只能在运行时判断iOS系统。

**Comment by devedbox** [comment]
__IPHONE_OS_VERSION_MAX_ALLOWED 用来判断当前SDK版本已选择需要编译的部分。如果不加的话，在低版本的Xcode里边引用高版本SDK的API的时候，静态编译通过不了！
