### ISSUE TITLE
返回上一个页面的时候的时候  前一个web页面会向上移动一部分。

### ISSUE THREAD

**Issue by deanli08** [devedbox/AXWebViewController#10]
返回上一个页面的时候的时候  前一个web页面会上移动一部分。

**Comment by devedbox** [comment]
提供示例，谢谢！

**Comment by deanli08** [comment]
你好  
   我使用的就是的demo ，测试环境真机7 10.2   
 这是第一个界面
http://chuantu.biz/t5/44/1482745389x2074127593.png
 然后随便点击一个界面进去
http://chuantu.biz/t5/44/1482745459x2074127593.png
然后出现close后 点击back返回第一个页面 （如下图可以明显看到界面上移了一部分）我使用我们的网站也是一样的
http://chuantu.biz/t5/44/1482745488x2074127593.png

**Comment by devedbox** [comment]
这可能是10.2的兼容问题，解决中...

**Comment by devedbox** [comment]
再次感谢对`AXWebViewController`的支持！
