### ISSUE TITLE
加载易企秀H5页面的时候出现页面的偏差

### ISSUE THREAD

**Issue by linjiaxing1992** [devedbox/AXWebViewController#14]
加载其他网址没问题，加载易企秀的h5页面出现了一些小问题，就是页面向下偏移了约一个导航栏的距离

具体加载网址 如：http://h5.eqxiu.com/s/dmc9DehK

**Comment by devedbox** [comment]
您好，你的iOS系统版本是多少？

**Comment by linjiaxing1992** [comment]
您好，目前只在iOS10上试过

**Comment by devedbox** [comment]
10.0还是10.2？

**Comment by linjiaxing1992** [comment]
10.2.1

**Comment by devedbox** [comment]
我在模拟器上试了没问题的，你方便给个截图吗？

**Comment by devedbox** [comment]
你使用的`AXWebViewController`是什么版本的？现在最新版是[0.4.1](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.1).

**Comment by devedbox** [comment]
#10

**Comment by linjiaxing1992** [comment]
😂重新下了新版本，就解决了，抱歉

**Comment by devedbox** [comment]
👍不客气，解决了就好😊
