### ISSUE TITLE
cocoapods 上的版本只更新到 0.3.4 ，怎么还没更新到最新版本（0.4.1）？

### ISSUE THREAD

**Issue by mingmingsky** [devedbox/AXWebViewController#15]
有些小问题，好像说最新版可以解决，麻烦作者有时间更新下

**Comment by devedbox** [comment]
cocoaPods上的版本已经更新到0.4.1了，请确保本地cocoaPods repo是最新的（使用`pod repo update --verbose`更新至最新库），然后运行`pod update AXWebViewController --verbose`即可
