### ISSUE TITLE
控制器有地方被强引用，导致不会被销毁

### ISSUE THREAD

**Issue by mkjfeng01** [devedbox/AXWebViewController#17]
问题在懒加载创建UIProgressView的地方这行代码
__weak typeof(self) wself = self;
    _progressView.ax_webViewController = wself;

**Comment by devedbox** [comment]
反馈已经收到了，会逐步进行处理。或者你也可以提一个PR给我，感谢！

**Comment by devedbox** [comment]
这个地方并不会产生循环应用，在`UIProgressView(WebKit)`中实现了`OBJC_ASSOCIATION_RETAIN_NONATOMIC`的方式来存储关联对象，但是在赋值给`ax_webViewController`的时候使用的是`webViewController`的弱引用关系，没有形成循环引用链. 如果你在使用的过程中确实因为这个地方造成了Crash，请再次issue我或者提交一个pr，谢谢对`AXWebViewController`的支持！
