### ISSUE TITLE
关于监听屏幕旋转

### ISSUE THREAD

**Issue by mkjfeng01** [devedbox/AXWebViewController#19]
Present出来的控制器，当加载2级或者以上次数网页后，iPhone和iPad版本左上角会出现`back`和`关闭`两个按钮，原因在`orientationChanged:`这个方法里边。
我感觉没必要增加屏幕旋转的通知，增加了反而有点多余，不知道您当初增加这个通知是出于什么考虑呢？可否说下？

**Comment by devedbox** [comment]
这是一个bug哈，当初设计的初衷是代码里如果支持横屏的话，`AXWebViewController`会监听并更新`NavigationItems`，刚才我检查了下，确实存在这个问题，在下个版本中会处理

**Comment by devedbox** [comment]
https://github.com/devedbox/AXWebViewController/commit/e2ccf3bea124557cffd1aa36da7251b1e474208a ：已修复

**Comment by devedbox** [comment]
[`v0.4.2`](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.2)：版本已更新
