### ISSUE TITLE
網頁上有tel: 會無法撥打電話

### ISSUE THREAD

**Issue by tentenlee100** [devedbox/AXWebViewController#20]
可否在
`- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler`
與
`- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType`
加上這段
```

    if ([navigationAction.request.URL.scheme isEqualToString:@"tel"]) {
        decisionHandler(WKNavigationActionPolicyCancel);
        
        NSString * mutStr = [NSString stringWithFormat:@"telprompt://%@",navigationAction.request.URL.resourceSpecifier];
        if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 10.0) {
            [[UIApplication sharedApplication] openURL:[NSURL URLWithString:mutStr] options:@{} completionHandler:^(BOOL success) {}];
        } else {
            [[UIApplication sharedApplication] openURL:[NSURL URLWithString:mutStr]];
        }
        
        return;
    }
```

出自於 http://www.jianshu.com/p/e65137ced997

**Comment by devedbox** [comment]
可以，我会在近期更新，或者你可以提一个pr给我！

**Comment by devedbox** [comment]
@tentenlee100 试试这个版本有没有解决问题呢：[`tag0.4.3`](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.3)

**Comment by tentenlee100** [comment]
要不要把email也放進去? 一些系統的功能

**Comment by devedbox** [comment]
@tentenlee100 下个版本加
