### ISSUE TITLE
cocoapods 加载bundle文件出错，闪退

### ISSUE THREAD

**Issue by mixlan123** [devedbox/AXWebViewController#21]
使用cocoapods 加载如下文件 为空。 pods中有该资源文件，但是加载不到。

#define kAX404NotFoundHTMLPath [[NSBundle mainBundle] pathForResource:@"AXWebViewController.bundle/html.bundle/404" ofType:@"html"]

**Comment by devedbox** [comment]
@mixlan123 系统版本是多少？xcode版本是多少？

**Comment by devedbox** [comment]
@mixlan123 试试这个版本有没有解决问题：[`tag0.4.3`](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.3)

**Comment by mixlan123** [comment]
系统 ios10.2   xcode8.2.1。之前是0.4.1版本。      更新到 tag0.4.3 解决了，谢谢！

**Comment by devedbox** [comment]
客气
