### ISSUE TITLE
不进入dealloc方法

### ISSUE THREAD

**Issue by CoderYB** [devedbox/AXWebViewController#23]
不进入dealloc方法

**Comment by devedbox** [comment]
看看代码

**Comment by devedbox** [comment]
@CoderYB 方便看看你的代码吗？这样有助于解决你的问题。

**Comment by IAFung** [comment]
你的demo就不释放 
 __weak typeof(self) wself = self;
    _progressView.ax_webViewController = wself;
这个代码注释了才会走dealloc

**Comment by devedbox** [comment]
@CoderYB @IAFung 感谢发现这个问题，一直都没注意到这个内存管理的问题！问题已解决：[v0.4.4](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.4)
