### ISSUE TITLE
有内存泄露，我在pop后，内存没有减少。

### ISSUE THREAD

**Issue by tigerZhang86** [devedbox/AXWebViewController#27]
有内存泄露，我在pop后，内存没有减少。

**Comment by devedbox** [comment]
@tigerZhang86 xcode所示的内存很不精确，况且一个对象是占用不了多少内存的，在xcode内存图里是看不出来的！经过调试，pop之后`AXWebViewController`的`dealloc`方法正常调用，也就是说`AXWebViewController`的实例被销毁了，所以在pop这个地方不存在内存泄漏.
