### ISSUE TITLE
網路慢時有些問題

### ISSUE THREAD

**Issue by tentenlee100** [devedbox/AXWebViewController#29]
AXWebViewController版本:  0.4.6
Xcode版本:  8.3.1
iOS/OSX版本:  9.3.5
依赖管理工具(cocoapods)版本: ? 1.2.1

在網路較慢的情況下，如果連到目標往只需要下載大量資料的時候，此時直接回上頁，會照成back會卡死，無法透過back的方式回到上一個頁面。

**Comment by devedbox** [comment]
@tentenlee100  确实存在这个问题，你有什么好的想法或者解决方案吗？

**Comment by tentenlee100** [comment]
@devedbox 嘗試解決中，只是先列出來讓你知道，若我解決的話在PR上來。

**Comment by devedbox** [comment]
@tentenlee100 一起搞！

**Comment by tentenlee100** [comment]
@devedbox 目前測試會卡住的狀況是
`- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
`
的時候
`        if (webVC.webView.canGoBack) `
是可以canGoBack的，但是後面執行
`[webVC.webView goBack];`
後他還是無法back回去，導致卡住。
然後就不知道怎麼處理了嗎....

**Comment by devedbox** [comment]
@tentenlee100 这个问题可能是由于Request超时导致的

**Comment by tentenlee100** [comment]
@devedbox 但是他就卡死了，看來知道原因了，在想要怎麼處理吧....

**Comment by devedbox** [comment]
@tentenlee100 试试最新版：`v0.5.0`.
