### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by johnsonlrd** [devedbox/AXWebViewController#33]
我直接把源码放进工程的时候，把你里面相关用到第三方库也加进去了，编译报错，“Apple Mach-O Linker Error: Apple command failed with exit code 1”，不加你的AXWebViewController是没问题的。是编译的时候，没找到头文件吗？？
Xcode 版本 8.3.1
iOS版本 10.3.1

**Comment by devedbox** [comment]
@johnsonlrd 能不能提供更多的错误信息？

**Comment by nonstriater** [comment]
使用Cocoapods 安装以后，有编译报错，源码集成ok

**Comment by devedbox** [comment]
@nonstriater 有详细的报错信息吗？

**Comment by nonstriater** [comment]
你写个demo，podfile里面加上 #pod 'AXWebViewController'， 编译就报错

**Comment by devedbox** [comment]
@johnsonlrd @nonstriater 版本：[`v0.4.8`](https://github.com/devedbox/AXWebViewController/releases/tag/0.4.8)已解决.

**Comment by wuwm** [comment]
@devedbox cocoapods 没有更新到0.4.8 现在是0.4.6

**Comment by devedbox** [comment]
@wuwm 你试试`pod repo update --verbose`更新下你的**pods repos**.
