### ISSUE TITLE
建议增加WKWebView的title的KVO

### ISSUE THREAD

**Issue by glary** [devedbox/AXWebViewController#35]
AXWebViewController版本: ? 1.2.7

Xcode版本: ? 8.3.2

iOS/OSX版本: ?8.0

依赖管理工具(cocoapods)版本: ?1.2.7

**Comment by devedbox** [comment]
@glary 最新版本：`v0.5.0`已发布.

**Comment by glary** [comment]
@devedbox  thank you

**Comment by glary** [comment]
还是没有添加title的KVO呀？

**Comment by devedbox** [comment]
增加title的kvo用意何在？

**Comment by glary** [comment]
就是 让tittle 跟随网页来显示，我发现一个bug，就是iOS8以上的时候h5那边用JS刷新了title，但是你这个控制器标题不会变。

**Comment by devedbox** [comment]
@glary 如果网页是SPA的，使用js来改变Title你确定web view的Title能跟随改变？

**Comment by glary** [comment]
http://web.hongbao.quzhuan.net.cn/index.html#!/fundsShop?temp=0   你用微信试试这个链接。这个是SPA的吧

**Comment by devedbox** [comment]
@glary 我试了，添加Title kvo之后没有收到回调. 微信的web 浏览是他自己的引擎，用的不是苹果原生的库.

**Comment by glary** [comment]
#if !AX_WEB_VIEW_CONTROLLER_USING_WEBKIT
    [self progressProxy];
#else
    [_webView addObserver:self forKeyPath:@"estimatedProgress" options:NSKeyValueObservingOptionNew context:NULL];
    [_webView addObserver:self forKeyPath:@"title" options:NSKeyValueObservingOptionNew context:NULL];

    /*
     [_webView.scrollView addObserver:self forKeyPath:@"backgroundColor" options:NSKeyValueObservingOptionNew context:NULL];
     */
#endif

**Comment by devedbox** [comment]
@glary 你试了可以吗？

**Comment by glary** [comment]
@devedbox  可以的，你点下面的更多推荐里的商品 可以看到标题会变。

**Comment by glary** [comment]
还有就是 你这个库依赖AFSecurityPolicy 会跟依赖AFNetworking 的项目冲突吗？ 我更想到0.5.0 报一个找不到AFSecurityPolicy.h的错。

**Comment by devedbox** [comment]
@glary 行，我改改.

**Comment by devedbox** [comment]
@glary 新版为：[`0.6.0`](https://github.com/devedbox/AXWebViewController/releases/latest).

**Comment by devedbox** [comment]
@glary 这个帖子含金量高啊！冲突那个是之前测试的，没修改，幸亏你及时发现了冲突的那个问题！

**Comment by glary** [comment]
thank you~
