### ISSUE TITLE
iOS 7.x的设备跳转AXWebViewController时，会出现闪退问题。

### ISSUE THREAD

**Issue by wanderer9527** [devedbox/AXWebViewController#41]
打扰一下，请教一个问题，我在使用AXWebViewController作为显示载体时，在7.x的设备上会出现闪退问题，其他系统版本显示正常。还是说 我在7.x的设备使用AXWebViewController，需要做其他处理？？

**Comment by devedbox** [comment]
@wanderer9527 把你报错的`调用栈`贴上来看看

**Comment by wanderer9527** [comment]
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
    frame #0: 0x399da9a8 libc++abi.dylib`__cxa_throw
    frame #1: 0x3a122da2 libobjc.A.dylib`objc_exception_throw + 250
    frame #2: 0x2f8a7ec4 CoreFoundation`+[NSException raise:format:] + 104
    frame #3: 0x3022f0ce Foundation`_NSDictionaryOfVariableBindings + 714
  * frame #4: 0x00979f3c NDWeather`-[AXWebViewController setupSubviews](self=0x18575900, _cmd="setupSubviews") at AXWebViewController.m:1341
    frame #5: 0x0096fb38 NDWeather`-[AXWebViewController viewDidLoad](self=0x18575900, _cmd="viewDidLoad") at AXWebViewController.m:209
    frame #6: 0x004694c8 NDWeather`-[ExDetailWebViewController viewDidLoad](self=0x18575900, _cmd="viewDidLoad") at ExDetailWebViewController.m:36
    frame #7: 0x320c94aa UIKit`-[UIViewController loadViewIfRequired] + 518
    frame #8: 0x320c9268 UIKit`-[UIViewController view] + 24
    frame #9: 0x3225536a UIKit`-[UINavigationController _startCustomTransition:] + 634
    frame #10: 0x32172d62 UIKit`-[UINavigationController _startDeferredTransitionIfNeeded:] + 418
    frame #11: 0x32172b6c UIKit`-[UINavigationController __viewWillLayoutSubviews] + 44
    frame #12: 0x32172b04 UIKit`-[UILayoutContainerView layoutSubviews] + 184
    frame #13: 0x320c4d58 UIKit`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 380
    frame #14: 0x31d4262a QuartzCore`-[CALayer layoutSublayers] + 142
    frame #15: 0x31d3de3a QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 350
    frame #16: 0x31d3dccc QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 16
    frame #17: 0x31d3d6de QuartzCore`CA::Context::commit_transaction(CA::Transaction*) + 230
    frame #18: 0x31d3d4ee QuartzCore`CA::Transaction::commit() + 314
    frame #19: 0x31d3721c QuartzCore`CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 56
    frame #20: 0x2f873254 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
    frame #21: 0x2f870bf8 CoreFoundation`__CFRunLoopDoObservers + 284
    frame #22: 0x2f870f3a CoreFoundation`__CFRunLoopRun + 730
    frame #23: 0x2f7dbebe CoreFoundation`CFRunLoopRunSpecific + 522
    frame #24: 0x2f7dbca2 CoreFoundation`CFRunLoopRunInMode + 106
    frame #25: 0x34735662 GraphicsServices`GSEventRunModal + 138
    frame #26: 0x3212814c UIKit`UIApplicationMain + 1136
    frame #27: 0x00552f6a NDWeather`main(argc=1, argv=0x27d40c10) at main.m:8
    frame #28: 0x3a62fab6 libdyld.dylib`start + 2

**Comment by devedbox** [comment]
@wanderer9527 是真机设备吧？

**Comment by wanderer9527** [comment]
没错，是在真机设备，iOS 7.1.2

**Comment by devedbox** [comment]
@wanderer9527  要不你帮忙看看什么原因吧？😆我没有iOS7的设备啊.

**Comment by devedbox** [comment]
@wanderer9527 再说现在iOS7都是古董了=  =

**Comment by wanderer9527** [comment]
@devedbox 已经定位到问题了。 下面这个宏定义有点问题，在iOS7.x的设备，返回YES， __IPHONE_OS_VERSION_MAX_ALLOWED = 103000  这个应该是SDK版本号？？
 
#ifndef AX_WEB_VIEW_CONTROLLER_USING_WEBKIT
#define AX_WEB_VIEW_CONTROLLER_USING_WEBKIT __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_8_0
#endif

**Comment by devedbox** [comment]
@wanderer9527 你看要不你提个pr上来呢？谢谢

**Comment by wanderer9527** [comment]
@devedbox 嘿嘿，不客气，我只是找到问题，没想到什么解决方法，   所以我目前从iOS8.x开始支持起，使用AXWeb.
