### ISSUE TITLE
发现2个问题

### ISSUE THREAD

**Issue by q876911695** [devedbox/AXWebViewController#43]
1，navigationBar的代理方法-(BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item 不应该写在viewControoler里；
2，Cookie设置是一个问题（未能解决，请求有什么好的方法吗？）

**Comment by devedbox** [comment]
你好

* 第一个问题不是代理的问题，是`Method Swizzling`的用法，使用`Responder Chain`来作为方法实现的地方，这样可以在任意VC写逻辑的地方实现之.
* 关于`Cookie`的设置，我用得少，不是特别清楚你什么需求，你可以看看网上的一些文章：`http://www.jianshu.com/p/42d0bcdfaaca`.

最后，还有其他什么问题，欢迎一起讨论

**Comment by q876911695** [comment]
Cookie我已经解决了，正在测试。如果没有问题再贴上来
