### ISSUE TITLE
web页面请求错误时，会出现无限刷新或无限重新请求的问题

### ISSUE THREAD

**Issue by wanderer9527** [devedbox/AXWebViewController#48]
##预期效果
加载web页面，当请求发生错误时，会跳转到一个web的错误提示界面；

##实际效果
使用AxWebVC加载web，当页面返回请求错误时，不会跳转错误页面，会在当前页面无限刷新；
pod ～0.5.0开始有这个问题的，～0.4.8不会有这个问题；

**Comment by devedbox** [comment]
请求的链接是什么？有没有图例？

**Comment by wanderer9527** [comment]
http://m.2339.com/7988164?clickfrom=12

**Comment by devedbox** [comment]
这个不是axweb的原因吧？并没有重复调用加载的代码啊

**Comment by wanderer9527** [comment]
pod update ～0.4.8 是没有问题的，update ～0.5.0就出现上述问题，（release：通过处理请求取消错误来处理标题混乱的情况，同时避免了KVO的使用），而加载这个网页返回的是error -999。用UIWebView或者系统浏览器Safari加载这个链接都是正常的。

**Comment by devedbox** [comment]
<img width="964" alt="2017-08-01 10 29 42" src="https://user-images.githubusercontent.com/8072556/28806770-5cb6819e-76a4-11e7-8996-e45d77560ab1.png">
你的请求是不是被服务器cancel了？

**Comment by devedbox** [comment]
你问问服务器对这个请求是怎么处理的，最好使用重定向！

**Comment by devedbox** [comment]
给你一个解决方案吧，你写一个VC继承AXWebVC，覆盖`- (void)webView:(WKWebView *)webView didFailNavigation:(null_unspecified WKNavigation *)navigation withError:(NSError *)error`这个方法，就可以解决你的问题了。

**Comment by wanderer9527** [comment]
好的，感谢。先用你的方法试试。
