### ISSUE TITLE
 请教一下，网页一直加载的问题

### ISSUE THREAD

**Issue by XYRZX** [devedbox/AXWebViewController#50]
打开优酷 https://www.youku.com 然后一直 加载不成功，应该是什么问题呐？但是换成Safari又没有问题

**Comment by devedbox** [comment]
看看代理方法的调用

**Comment by devedbox** [comment]
Check out [`v0.7.0`](https://github.com/devedbox/AXWebViewController/releases/tag/0.7.0).
