### ISSUE TITLE
如果根控制器就是AXWebViewController所在的nav的话关闭有问题

### ISSUE THREAD

**Issue by lahala** [devedbox/AXWebViewController#55]
代码如下： 
AXWebViewController *webVC = [[AXWebViewController alloc] initWithAddress:@"http://www.baidu.com"];
    webVC.showsToolBar = NO;
    webVC.webView.allowsLinkPreview = YES;
    UINavigationController *nav = [[UINavigationController alloc]initWithRootViewController:webVC];
    self.window = [[UIWindow alloc] init];
    self.window.backgroundColor = [UIColor whiteColor];
    self.window.frame = [UIScreen mainScreen].bounds;
    self.window.rootViewController = nav;
这样的话 里面的关闭 是不起作用的，望指教！！谢谢

**Comment by devedbox** [comment]
Check out [`v0.7.0`](https://github.com/devedbox/AXWebViewController/releases/tag/0.7.0).
