### ISSUE TITLE
push界面，刷新界面为空时，pop

### ISSUE THREAD

**Issue by KKLater** [devedbox/AXWebViewController#6]
-[WKScrollView _systemGestureStateChanged:]: message sent to deallocated instance 0x7fff140f10d0

**Comment by KKLater** [comment]
iOS8.4

**Comment by devedbox** [comment]
崩溃了吗？

**Comment by devedbox** [comment]
@KKLater 崩溃了吗？

**Comment by KKLater** [comment]
很对不起，问题原因找到了。是我们团队一个成员写错了方法导致的。在9、10上没有崩溃，8上崩溃了。目前已经修复了。不过这个组件里面的宏判定版本会出问题。我们在宏判定之后又加了systemVersion判定来保证绝对安全。


发自网易邮箱大师
在2016年09月22日 13:57，ax 写道:

@KKLater 崩溃了吗？

**Comment by KKLater** [comment]
很抱歉，昨晚才弄完了项目，忘记来更正信息了。辛苦大神们，把这个关掉吧。十分感谢您的开源！
在2016年09月22日 13:57，ax 写道:

@KKLater 崩溃了吗？

**Comment by devedbox** [comment]
@KKLater 感谢支持，后续版本会陆续的完善和更新！
