### ISSUE TITLE
AXPopNavigationController 死循环!

### ISSUE THREAD

**Issue by shenguanjiejie** [devedbox/AXWebViewController#60]
![image](https://user-images.githubusercontent.com/9425605/33765224-c7d30024-dc52-11e7-8690-e5f00ca76051.png)
nextViewController为nil,while循环跳不出了...
0.6.1和0.7.0都会这样

**Comment by devedbox** [comment]
@shenguanjiejie xcode几？iOS几？

**Comment by shenguanjiejie** [comment]
@devedbox 
好像并不是你的问题 我把AXWebViewController删掉后 还是会出现其他死循环. 是HyperioniOS这个库的问题 我去提给他们吧.
