### ISSUE TITLE
希望增加能够修改UserAgent的方法。

### ISSUE THREAD

**Issue by iodefog** [devedbox/AXWebViewController#64]
现在继承你AXWebViewController，而后在viewDidLoad中修改UserAgent，不生效。所以希望你那边能增加这个方法，也算一个很常用的方法吧

**Comment by devedbox** [comment]
@iodefog 设置`webViewController.webView.customUserAgent`不生效么？
<img width="733" alt="2018-01-13 1 45 00" src="https://user-images.githubusercontent.com/8072556/34903226-13518f76-f868-11e7-85be-0731f834e336.png">

**Comment by devedbox** [comment]
@iodefog 需要在`viewDidLoad`之前进行设置，`viewDidLoad`之后webView已经加载内容了.

**Comment by iodefog** [comment]
close
