### ISSUE TITLE
通过这个加载APP页面为什么不能跳到AppStore？

### ISSUE THREAD

**Issue by brucehelen** [devedbox/AXWebViewController#7]
加载App地址，会在控制器中显示AppStore网页，怎么设置才能跳转到AppStore，就像微信支付宝那样？

**Comment by devedbox** [comment]
可否提供下示例代码？待我重现一下问题看是不是bug

**Comment by brucehelen** [comment]
测试很简单，随便加载一个AppStore APP地址，使用系统的UIWebView加载这个地址会跳转到AppStore中。https://itunes.apple.com/cn/app/xian-jin-jie-kuan-jie-qian/id1135344112?mt=8

**Comment by devedbox** [comment]
已经解决了。建议使用这个方式打开AppStore：itms-apps://itunes.apple.com/cn/app/xian-jin-jie-kuan-jie-qian/id1135344112?mt=8
