### ISSUE TITLE
iOS8以上如果要添加cookies是否可以实现呢？

### ISSUE THREAD

**Issue by DreamXiao** [devedbox/AXWebViewController#8]
后台需要我们这边设置cookies。。。

**Comment by DreamXiao** [comment]
自己手动添加了一些，后台是可以看到的，但是觉得还是有些小问题。

**Comment by devedbox** [comment]
推荐新建一个：WebViewController:AXWebViewController 在里边进行操作。

**Comment by DreamXiao** [comment]
好的。谢谢。目前是直接引入文件，在源代码里面修改的。
