### ISSUE TITLE
发现用继承的方法 调用 loadUrl ，还是现实404notFound

### ISSUE THREAD

**Issue by linjiaxing1992** [devedbox/AXWebViewController#9]
在Xcode8上

**Comment by linjiaxing1992** [comment]
我发现注释掉viewDidLoad里面的if判断语句中的[self loadURL:[NSURL fileURLWithPath:kAX404NotFoundHTMLPath]];就可以解决了，但这明显是不行的

**Comment by devedbox** [comment]
麻烦提供下示例代码@linjiaxing1992

**Comment by linjiaxing1992** [comment]
#import "PushViewController.h"

@interface PushViewController ()

@end

@implementation PushViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self loadURL:[NSURL URLWithString:@"https://www.baidu.com"]];
}

下载的demo也是继承的方法不能加载页面,直接显示404NotFound的界面

环境 ：Xcode8.1 与 iOS 10.1

**Comment by devedbox** [comment]
需要在初始化VC的时候设置URL，注意方法的调用顺序。-loadURL只是加载一个普通的URL，并不会在加载的时候设置URL的Ivar，你可以使用KVC试试

**Comment by linjiaxing1992** [comment]
之前只是alloc init ，并没有设置url  。
已解决 谢谢

**Comment by devedbox** [comment]
不客气
